name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: Validate data.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Validate json schema
        run: npm run validate-schema

      - name: Validate json data
        run: npm run validate-data
